### ISSUE TITLE
mediateurfevad.fr is broken with EasyList Cookie enabled

### ISSUE THREAD

**Issue by Rudloff** [easylist/easylist#12517]
### List the website(s) you're having issues:

`https://www.mediateurfevad.fr/`

### What happens?

A loader is displayed forever.

### List Subscriptions you're using:

```
listset (total-discarded, last updated): 
  added: 
    fanboy-cookiemonster: 35989-81, now
  default: 
    user-filters: 0-0, never
    ublock-filters: 32750-186, now
    ublock-badware: 4216-3, now
    ublock-privacy: 231-0, now
    ublock-abuse: 75-0, now
    ublock-unbreak: 1847-2, now
    easylist: 68494-611, now
    easyprivacy: 27362-581, now
    urlhaus-1: 4991-0, now
    plowe-0: 3646-3, now
    FRA-0: 29299-352, now
    ublock-quick-fixes: 204-0, now
```

### Your settings

- OS/version: Ubuntu 22.04 LTS
- Browser/version: Firefox 102.0.1
- Adblock Extension/version: uBlock Origin 1.43.0

### Other details:

![Screenshot](https://user-images.githubusercontent.com/840125/178041795-747f40fe-517d-4386-9c50-6c0d8b3ebefd.png)

I get this error in the console:
```
Uncaught TypeError: jQuery().cookieInfo is not a function
    <anonymous> https://www.mediateurfevad.fr/:320
    jQuery 8
www.mediateurfevad.fr:320:16
```
