### ISSUE TITLE
justwatch.com: GDPR pop-in not blocked by Easylist Cookie

### ISSUE THREAD

**Issue by Rudloff** [easylist/easylist#12526]
### List the website(s) you're having issues:

`https://www.justwatch.com/`

### What happens?

I get a huge pop-in and can't interact with the website unless I answer.

### List Subscriptions you're using:

```
listset (total-discarded, last updated): 
  added: 
    fanboy-cookiemonster: 36022-81, 21h.22m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32772-186, 21h.23m
    ublock-badware: 4216-3, 21h.23m
    ublock-privacy: 231-0, 21h.23m
    ublock-abuse: 75-0, 21h.23m
    ublock-unbreak: 1849-2, 21h.23m
    easylist: 68507-611, 21h.23m
    easyprivacy: 27369-581, 21h.23m
    urlhaus-1: 5081-0, 21h.22m
    plowe-0: 3646-3, 21h.22m
    FRA-0: 29299-352, 21h.22m
    ublock-quick-fixes: 204-0, 21h.22m
```

### Your settings

- OS/version: Ubuntu 22.04 LTS
- Browser/version: Firefox 102.0.1
- Adblock Extension/version: uBlock Origin 1.43.0

### Other details:

![Screenshot](https://user-images.githubusercontent.com/840125/178141327-0fe37965-1af4-4951-8d2c-cb4c727f45a2.png)
