### ISSUE TITLE
[Cookie List] Angular.js based cookie modal popups

### ISSUE THREAD

**Issue by jesus2099** [easylist/easylist#12559]
### List the website(s) you're having issues:

`https://www.moncompteformation.gouv.fr/espace-public/salarie-de-droit-prive`

### What happens?

The cookie modal popup relies on Angular.js and adds a `cdk-global-scrollblock` CSS class to the page main `<html>` topmost tag.
This prevents scrolling.

Easylist Cookie List removes the cookie modal popup but not this `html.cdk-global-scrollblock` class `position: fixed` attribute, and thus the page cannot be scrolled. Vertical scrollbar is prevented by the `position: fixed`, specifically:

```css
.cdk-global-scrollblock {
	position: fixed; /* this one is the culprit */
	width: 100%;
	overflow-y: scroll
}
```

### List Subscriptions you're using:

I pinpointed Easylist Cookie List: https://secure.fanboy.co.nz/fanboy-cookiemonster.txt

### Your settings

- OS/version: Windows 10
- Browser/version: Vivaldi 5.3.2679.68 (Stable channel) (64 bits) 
- Adblock Extension/version: n/a

### Other details:

See where I found this: https://forum.vivaldi.net/post/598236
