### ISSUE TITLE
bm-lille.fr: broken overlay with Fanboy Annoyance

### ISSUE THREAD

**Issue by prudloff-insite** [easylist/easylist#12697]
### List the website(s) you're having issues:

```
https://bm-lille.fr/
```

### What happens?

The cookie banner is hidden but there is still an overlay so I can't interact with the website.

### List Subscriptions you're using:

```
listset (total-discarded, last updated): 
  added: 
    fanboy-annoyance: 76372-284, now
  default: 
    user-filters: 0-0, never
    ublock-filters: 32946-180, now
    ublock-badware: 4213-0, now
    ublock-privacy: 240-0, now
    ublock-abuse: 76-0, now
    ublock-unbreak: 1848-0, now
    easylist: 68796-643, now
    easyprivacy: 27449-580, now
    plowe-0: 3640-3, now
    FRA-0: 29620-354, now
    urlhaus-1: 4937-0, now
```

### Your settings

- OS/version: Linux Mint 20
- Browser/version: Firefox 102.0.1
- Adblock Extension/version: uBlock Origin 1.43.0

### Other details:

![image](https://user-images.githubusercontent.com/50333926/180969325-172285c9-d91f-4223-93d6-95214b24e471.png)
