### ISSUE TITLE
sncf-connect.com

### ISSUE THREAD

**Issue by Rudloff** [easylist/easylist#13213]
### List the website(s) you're having issues:

`https://www.sncf-connect.com/app/home/search`

### What happens?

Without Fanboy's Annoyance, when submiting the search (_Voir les prix_ button), it browses to `https://www.sncf-connect.com/app/interstitiel` (loading screen) then to the search results.
With the filter enabled, it browses to `https://www.sncf-connect.com/app/interstitiel` then to this error page: `https://www.sncf-connect.com/erreur-interne`

### List Subscriptions you're using:

```
listset (total-discarded, last updated): 
  added: 
    fanboy-annoyance: 80158-237, never
  default: 
    user-filters: 0-0, never
    ublock-filters: 33249-204, 4m
    ublock-badware: 4221-0, 4m
    ublock-privacy: 275-0, 4m
    ublock-abuse: 76-0, 4m
    ublock-unbreak: 1862-0, 4m
    easylist: 64971-1284, 4m
    easyprivacy: 27487-614, 3m
    urlhaus-1: 7510-0, 4m
    plowe-0: 3671-3, 4m
    FRA-0: 30588-350, 4m
    ublock-quick-fixes: 424-0, 4m
```

### Your settings

- OS/version: Ubuntu 22.04.1 LTS
- Browser/version: Firefox 104.0.1
- Adblock Extension/version: uBlock Origin 1.44.2

### Other details:

![image](https://user-images.githubusercontent.com/840125/188517007-acf0cdcd-16b9-4e31-a377-ffd4c3bc620f.png)
