### ISSUE TITLE
synlab.fr

### ISSUE THREAD

**Issue by Rudloff** [easylist/easylist#13687]
### List the website(s) you're having issues:

```
https://synlab.fr/
```

### What happens?

I can't interact with the page when Fanboy's Annoyance is enabled.

### List Subscriptions you're using:

```
listset (total-discarded, last updated): 
  added: 
    fanboy-annoyance: 80761-297, never
  default: 
    user-filters: 0-0, never
    ublock-filters: 33840-46, 2m
    ublock-badware: 4363-0, 2m
    ublock-privacy: 274-0, 2m
    ublock-abuse: 76-0, 2m
    ublock-unbreak: 1881-1, 2m
    easylist: 62498-1566, 2m
    easyprivacy: 30695-1705, 2m
    urlhaus-1: 8724-0, 2m
    plowe-0: 3671-3, 2m
    FRA-0: 30898-484, 2m
    ublock-quick-fixes: 341-0, 2m
```

### Your settings

- OS/version: Ubuntu 22.04.1 LTS
- Browser/version: Firefox 105.0.3
- Adblock Extension/version: uBlock Origin 1.44.4

### Other details:

![image](https://user-images.githubusercontent.com/840125/194716574-c2789863-84ba-4a5a-aa7a-8eb053d93062.png)
