### ISSUE TITLE
taxis.thetrainline.com

### ISSUE THREAD

**Issue by Rudloff** [easylist/easylist#14073]
### List the website(s) you're having issues:

`https://taxis.thetrainline.com/fr-fr/trip-details`

### What happens?

The cookie banner is not blocked by Fanboy's Annoyance List.

### List Subscriptions you're using:

```yaml
listset (total-discarded, last updated): 
  added: 
    fanboy-annoyance: 82476-314, 3h.30m
  default: 
    user-filters: 0-0, never
    ublock-filters: 31914-57, 3h.30m
    ublock-badware: 3962-0, 3h.30m
    ublock-privacy: 285-0, 3h.30m
    ublock-abuse: 76-0, 3h.30m
    ublock-unbreak: 1906-0, 3h.30m
    easylist: 64372-634, 3h.30m
    easyprivacy: 30787-1708, 3h.30m
    urlhaus-1: 10851-0, 3h.30m
    plowe-0: 3668-3, 3h.30m
    FRA-0: 30809-536, 3h.30m
    ublock-quick-fixes: 522-0, 3h.30m
```

### Your settings

- OS/version: Ubuntu 22.04.1 LTS
- Browser/version: Firefox 106.0.5
- Adblock Extension/version: uBlock Origin 1.44.4

### Other details:

![image](https://user-images.githubusercontent.com/840125/200693357-233fcd71-e26b-4d25-8a58-042b4fa56e90.png)
