### ISSUE TITLE
www.credit-cooperatif.coop

### ISSUE THREAD

**Issue by Rudloff** [easylist/easylist#14288]
### List the website(s) you're having issues:

`https://www.credit-cooperatif.coop/espace-client/compte/avance`

### What happens?

Scrolling is disabled when Fanboy's Annoyance filter is enabled.

### List Subscriptions you're using:

```yaml
listset (total-discarded, last-updated): 
  added: 
    fanboy-annoyance: 83460-360, now
  default: 
    user-filters: 0-0, never
    ublock-filters: 32377-171, 3m
    ublock-badware: 4130-1, 3m
    ublock-privacy: 307-0, 3m
    ublock-abuse: 77-0, 3m
    ublock-unbreak: 1922-2, 3m
    easylist: 65093-680, 3m
    easyprivacy: 30920-1739, 3m
    urlhaus-1: 9935-0, 3m
    plowe-0: 3679-3, 3m
    FRA-0: 30230-457, 3m
    ublock-quick-fixes: 393-0, 3m
```

### Your settings

- OS/version: Ubuntu 22.04.1
- Browser/version: Firefox 107.0.1
- Adblock Extension/version: uBlock Origin 1.45.2

### Other details:

It happens because the cookie dialog adds this on the body:
```css
body.bpce-modal-is-open {
	overflow-y: hidden;
}
```

Unfortunately, you need a bank account in this bank to reproduce this.
