### ISSUE TITLE
faq.whatsapp.com

### ISSUE THREAD

**Issue by Rudloff** [easylist/easylist#14368]
### List the website(s) you're having issues:

`https://faq.whatsapp.com/539178204879377/?helpref=uf_share`

### What happens?

Cookie banner is not hidden.

### List Subscriptions you're using:

```yaml
listset (total-discarded, last-updated): 
  added: 
    fanboy-annoyance: 83662-370, 1m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32295-164, 1m
    ublock-badware: 4163-1, 1m
    ublock-privacy: 301-0, 1m
    ublock-abuse: 77-0, 1m
    ublock-unbreak: 1928-2, 1m
    easylist: 66080-748, 1m
    easyprivacy: 30976-1739, 1m
    urlhaus-1: 7578-0, 1m
    plowe-0: 3678-3, 1m
    FRA-0: 30537-458, 1m
    ublock-quick-fixes: 427-0, 1m
```

### Your settings

- OS/version: Ubuntu 22.04.1
- Browser/version: Firefox 107.0.1
- Adblock Extension/version: uBlock Origin 1.45.2

### Other details:

![image](https://user-images.githubusercontent.com/840125/206856274-af08ab59-b538-4238-a974-bbd70af65646.png)
