### ISSUE TITLE
www.tf1info.fr

### ISSUE THREAD

**Issue by Rudloff** [easylist/easylist#14415]
### List the website(s) you're having issues:

`https://www.tf1info.fr/politique/affaire-adrien-quatennens-gerald-darmanin-va-porter-plainte-en-diffamation-contre-le-depute-lfi-2241841.html`

### What happens?

When Fanboy's Annoyance is enabled, I can't scroll the page.

### List Subscriptions you're using:

```yaml
listset (total-discarded, last-updated): 
  added: 
    fanboy-annoyance: 83662-372, 5d.7h.51m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32286-169, 1d.2h.11m
    ublock-badware: 4049-1, 1d.2h.10m
    ublock-privacy: 301-0, 1d.2h.9m
    ublock-abuse: 77-0, 1d.2h.8m
    ublock-unbreak: 1928-2, 1d.2h.7m
    easylist: 66080-749, 5d.7h.51m
    easyprivacy: 30991-1739, now
    urlhaus-1: 9864-0, 1h.35m
    plowe-0: 3678-3, 5d.7h.51m
    FRA-0: 30515-458, 1d.2h.6m
    ublock-quick-fixes: 491-0, 1h.34m
 ```

### Your settings

- OS/version: Ubuntu 22.04.1
- Browser/version: Firefox 108.0 
- Adblock Extension/version: uBlock Origin 1.45.2

### Other details:

For some reason, I can scroll if I enable Fanboy's Annoyance but disable EasyPrivacy.
