### ISSUE TITLE
www.numerama.com

### ISSUE THREAD

**Issue by Rudloff** [easylist/easylist#14425]
### List the website(s) you're having issues:

`https://www.numerama.com/politique/1210498-il-a-tellement-force-que-jai-fini-par-ceder-enquete-sur-le-youtubeur-inthepanda-mis-en-cause-par-plusieurs-personnes.html`

### What happens?

Cookie banner is not blocked by Fanboy's Annoyance.

### List Subscriptions you're using:

```yaml
listset (total-discarded, last-updated): 
  added: 
    fanboy-annoyance: 83854-404, 1d.12h.59m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32286-54, 2d.15h.11m
    ublock-badware: 4049-1, 2d.15h.10m
    ublock-privacy: 301-0, 2d.15h.9m
    ublock-abuse: 77-0, 2d.15h.8m
    ublock-unbreak: 1928-2, 2d.15h.7m
    easylist: 62168-780, 15h.42m
    easyprivacy: 30991-1740, 1d.12h.59m
    urlhaus-1: 9370-0, 13h.12m
    plowe-0: 3678-3, 6d.20h.52m
    FRA-0: 30515-569, 2d.15h.6m
    ublock-quick-fixes: 492-0, 13h.11m
```

### Your settings

- OS/version: Ubuntu 22.04.1
- Browser/version: Firefox 108.0 
- Adblock Extension/version: uBlock Origin 1.45.2

### Other details:

![image](https://user-images.githubusercontent.com/840125/208236072-7d0d9695-f8be-492a-9fff-ed1f8280bebd.png)
