### ISSUE TITLE
www.leslipfrancais.fr

### ISSUE THREAD

**Issue by Rudloff** [easylist/easylist#14543]
### List the website(s) you're having issues:

`https://www.leslipfrancais.fr/`

### What happens?

I can't interact with the page when Fanboy’s Annoyance filter is enabled.

### List Subscriptions you're using:

```yaml
listset (total-discarded, last-updated): 
  added: 
    fanboy-annoyance: 84579-399, never
  default: 
    user-filters: 0-0, never
    ublock-filters: 32311-54, 1d.23h.2m
    ublock-badware: 4272-0, 1d.23h.1m
    ublock-privacy: 307-0, 1d.23h
    ublock-abuse: 77-0, 1d.22h.59m
    ublock-unbreak: 1924-1, 1d.22h.58m
    easylist: 64996-649, 2d.22h.44m
    easyprivacy: 30843-1741, 2d.22h.45m
    urlhaus-1: 7151-0, 22h.54m
    plowe-0: 3672-2, 6d.18h.58m
    FRA-0: 30078-504, 1d.22h.57m
    ublock-quick-fixes: 444-1, 22h.53m
```

### Your settings

- OS/version: Ubuntu 22.04.1
- Browser/version: Firefox 108.0.1
- Adblock Extension/version: uBlock Origin 1.46.0

### Other details:

![image](https://user-images.githubusercontent.com/840125/210170169-b516bf5f-63de-4bdf-8a79-675b6e630ca9.png)
