### ISSUE TITLE
assure.ameli.fr

### ISSUE THREAD

**Issue by Rudloff** [easylist/easylist#14544]
### List the website(s) you're having issues:

`https://assure.ameli.fr/PortailAS/appmanager/PortailAS/assure?_somtc=true#idPopupWARecueilConsentement`

### What happens?

A cookie banner is displayed.

### List Subscriptions you're using:

```yaml
listset (total-discarded, last-updated): 
  added: 
    fanboy-annoyance: 84579-399, 45m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32311-163, 1d.23h.49m
    ublock-badware: 4272-0, 1d.23h.48m
    ublock-privacy: 307-0, 1d.23h.47m
    ublock-abuse: 77-0, 1d.23h.46m
    ublock-unbreak: 1924-2, 1d.23h.45m
    easylist: 64996-649, 2d.23h.31m
    easyprivacy: 30850-1739, 45m
    urlhaus-1: 7151-0, 23h.41m
    plowe-0: 3672-2, 6d.19h.45m
    FRA-0: 30078-397, 1d.23h.44m
    ublock-quick-fixes: 444-0, 23h.40m
```

### Your settings

- OS/version: Ubuntu 22.04.1
- Browser/version: Firefox 108.0.1
- Adblock Extension/version: uBlock Origin 1.46.0

### Other details:

![image](https://user-images.githubusercontent.com/840125/210171274-d66980ad-035d-462b-b865-4796bfeba6ec.png)
