### ISSUE TITLE
https://web3.cmvm.pt/sdi/fundos/carteiras/fim/carteiras_fim.cfm

### ISSUE THREAD

**Issue by guicale** [easylist/easylist#14586]
### List the website(s) you're having issues:
`https://web3.cmvm.pt/sdi/fundos/carteiras/fim/carteiras_fim.cfm`
`https://web3.cmvm.pt/english/sdi/fundos/carteiras/fim/carteiras_fim.cfm`

### What happens?
Clicking any of the links from the main list on the page (to the right of the sidebar, under "Composição discriminada da carteira dos fundos de investimento mobiliário") leads to an error page.

### List Subscriptions you're using:
```
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2066-1, 26m
    adguard-spyware-url: 871-126, 33m
    fanboy-cookiemonster: 44491-191, never
    spa-1: 4864-14, 33m
  default: 
    user-filters: 1-0, never
    ublock-filters: 32373-83, 25m
    ublock-badware: 4238-0, 33m
    ublock-privacy: 305-2, 33m
    ublock-abuse: 77-0, 33m
    ublock-unbreak: 1927-2, 33m
    easylist: 61414-682, 33m
    easyprivacy: 30878-1753, 33m
    urlhaus-1: 7152-0, 33m
    plowe-0: 3671-2, 33m
    ublock-quick-fixes: 452-1, 33m
```

### Your settings

- OS/version: Windows 10 22H2
- Browser/version: Firefox 108.0.1
- Adblock Extension/version: uBlock Origin 1.46.0

### Other details:
This error seems to be caused by the blocking of `https://web3.cmvm.pt/js/jcookie.js` by a rule on the "EasyList Cookie" list. (Another rule from the "uBlock filters" list, which blocked `https://web3.cmvm.pt/js/jquery.watch.js`, also contributed to the error, which I've reported in the respective issue tracker at uBlockOrigin/uAssets#16221)
