### ISSUE TITLE
EP: gazeshop.com

### ISSUE THREAD

**Issue by seia-soto** [easylist/easylist#15504]
### List the website(s) you're having issues:

- https://www.gazeshop.com/product/detail.html?product_no=8890&cate_no=1184&display_group=1

### What happens?

User Tracking.

### List Subscriptions you're using:

```
listset (total-discarded, last-updated): 
  added: 
    https://github.com/seia-soto/filter-kr/raw/master/filter.txt: 268-0, 2m
    https://github.com/yous/YousList/raw/master/youslist.txt: 7845-5, 2d.3h.41m
    block-lan: 47-0, 6d.4h.55m
    curben-phishing: 66243-2, 23h.35m
    curben-pup: 192-0, 23h.34m
    dpollock-0: 11349-13, 6d.4h.55m
    fanboy-annoyance: 80945-368, 5d.6h.48m
    fanboy-cookiemonster: 46522-46522, 5d.6h.48m
    fanboy-social: 21050-21035, 1d.3h.36m
    fanboy-thirdparty_social: 68-19, 6d.4h.55m
  default: 
    user-filters: 0-0, never
    easylist: 64241-294, 2d.3h.46m
    easyprivacy: 30787-1289, 2d.3h.45m
    plowe-0: 3753-1315, 6d.4h.55m
    ublock-abuse: 78-0, 6d.4h.55m
    ublock-badware: 6506-142, 2d.3h.44m
    ublock-filters: 33455-132, 2d.3h.43m
    ublock-privacy: 302-8, 6d.4h.55m
    ublock-quick-fixes: 365-21, 23h.33m
    ublock-unbreak: 1967-47, 2d.3h.42m
    urlhaus-1: 7215-3, 23h.32m
```

### Your settings

- OS/version: macOS 13
- Browser/version: Ungoogled-Chromium v111
- Adblock Extension/version: uBO v1.48.4

### Other details:

- Service of `smlog.co.kr`: from https://cdn.smlog.co.kr/core/smart.js and Fetch/XHR to `a25.smlog.co.kr`
- Service of unknown but called `retaku`: Fetch/XHR to `pxl.retaku.net`
