### ISSUE TITLE
www.aap.santelys.fr

### ISSUE THREAD

**Issue by prudloff-insite** [easylist/easylist#15529]
### List the website(s) you're having issues:

`https://www.aap.santelys.fr/fr/`

### What happens?

I can't interact with the page when Fanboy's Annoyance is enabled.

### List Subscriptions you're using:

```yaml
listset (total-discarded, last-updated): 
  added: 
    fanboy-annoyance: 80268-365, never
  default: 
    user-filters: 0-0, never
    ublock-filters: 34627-131, 1m
    ublock-badware: 6608-2, 1m
    ublock-privacy: 344-0, 1m
    ublock-abuse: 78-0, 1m
    ublock-unbreak: 1992-1, 1m
    easylist: 64571-1016, 1m
    easyprivacy: 30818-1771, 1m
    plowe-0: 3750-1, 1m
    FRA-0: 29054-389, 1m
    urlhaus-1: 7557-1, 1m
```

### Your settings

- OS/version: Linux Mint 21
- Browser/version: Firefox 112.0
- Adblock Extension/version: uBlock Origin 1.48.4

### Other details:

![image](https://user-images.githubusercontent.com/50333926/231985956-cddd0fb5-2b06-4e78-925b-dd4ff7e2790b.png)
