### ISSUE TITLE
www.iledefrance-mobilites.fr

### ISSUE THREAD

**Issue by Rudloff** [easylist/easylist#16263]
#### List the website(s) you're having issues with:

`https://www.iledefrance-mobilites.fr/titres-et-tarifs/detail/liberte-plus`

#### What happens?

When EasyList Cookie List is enabled, I can't scroll the page at all.

#### Screenshot(s) 

![image](https://github.com/easylist/easylist/assets/840125/d68cea3a-3cf2-4a43-913a-d3ee0d01c47c)

#### Filter lists you're using:

```yaml
listset (total-discarded, last-updated): 
 added: 
  fanboy-cookiemonster: 47417-228, never
 default: 
  user-filters: 0-0, never
  ublock-filters: 34424-45, 4m
  ublock-badware: 7347-0, 4m
  ublock-privacy: 436-0, 4m
  ublock-unbreak: 2045-0, 4m
  ublock-quick-fixes: 203-0, 4m
  easylist: 66971-706, 4m
  easyprivacy: 30856-610, 4m
  urlhaus-1: 6673-0, 4m
  plowe-0: 3734-2, 4m
  FRA-0: 28271-441, 4m
```

#### Your settings:

- OS/version: Ubuntu 22.04.2 LTS
- Browser/version: Firefox 114.0
- Adblock extension/version: uBlock Origin 1.49.2
