### ISSUE TITLE
Cookie Notices list breaks search on ouvaton.coop

### ISSUE THREAD

**Issue by Rudloff** [easylist/easylist#17750]
#### List the website(s) you're having issues with:

`https://ouvaton.coop/`

#### What happens?

When the *EasyList – Cookie Notices* list is enabled, clicking on the search button in the header does nothing.

#### Screenshot(s) 

![image](https://github.com/easylist/easylist/assets/840125/8d106412-cc47-4769-9439-cca0dce9f493)

#### Filter lists you're using:

```yaml
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 48842-226, now
  ublock-cookies-easylist: 497-0, now
 default:
  user-filters: 0-0, never
  ublock-filters: 36148-218, now
  ublock-badware: 7447-5, now
  ublock-privacy: 661-0, now
  ublock-unbreak: 2194-1, now
  ublock-quick-fixes: 171-7, 29m
  easylist: 75227-781, 1m
  easyprivacy: 32865-725, 1m
  urlhaus-1: 11425-0, now
  plowe-0: 3723-1, now
  FRA-0: 28551-336, now
```

#### Your settings:

- OS/version: Ubuntu 23.10
- Browser/version: Firefox 119.0
- Ad block extension/version: uBlock Origin 1.53.0
