### ISSUE TITLE
www.numerama.com

### ISSUE THREAD

**Issue by Rudloff** [easylist/easylist#17989]
#### List the website(s) you're having issues with:

`https://www.numerama.com/pop-culture/1585224-le-jeu-de-zombies-the-day-before-est-la-plus-grosse-supercherie-de-2023.html`

#### What happens?

The cookie banner is not blocked.

#### Screenshot(s) 

![image](https://github.com/easylist/easylist/assets/840125/f08c875e-784e-4386-bff8-9eb5bcc446c3)

#### Filter lists you're using:

```yaml
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 49164-228, now
  ublock-cookies-easylist: 657-0, now
 default:
  user-filters: 0-0, never
  ublock-filters: 36764-146, 1h.3m
  ublock-badware: 7610-11, 1h.3m
  ublock-privacy: 931-4, 1h.3m
  ublock-unbreak: 2203-0, 1h.3m
  ublock-quick-fixes: 186-2, 1h.3m
  easylist: 75374-776, 1h.3m
  easyprivacy: 33094-804, 1h.3m
  urlhaus-1: 10745-0, now
  plowe-0: 3777-1, now
  FRA-0: 28803-339, now
```

#### Your settings:

- OS/version: Ubuntu 23.10
- Browser/version: Firefox 120.0.1
- Ad block extension/version: uBlock Origin 1.54.0
