### ISSUE TITLE
www.veritable-potager.fr

### ISSUE THREAD

**Issue by Rudloff** [easylist/easylist#18348]
#### List the website(s) you're having issues with:

`https://www.veritable-potager.fr/fr/nous-contacter`

#### What happens?

Cookie Notices filter hides the privacy notice checkbox so the form can't be submitted.

#### Screenshot(s) 

With filter:
![image](https://github.com/easylist/easylist/assets/840125/569624b2-7a09-43eb-80ce-56f0a4fd3e78)

Without filter:
![image](https://github.com/easylist/easylist/assets/840125/2cfb2059-e8b1-4028-8b5a-dc1c3fa5eabf)

#### Filter lists you're using:

```yaml
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 49349-189, never
  ublock-cookies-easylist: 898-0, never
 default:
  user-filters: 0-0, never
  ublock-filters: 37097-184, 3h.54m Δ
  ublock-badware: 7766-11, 3h.54m Δ
  ublock-privacy: 992-0, 3h.54m Δ
  ublock-unbreak: 2237-1, 3h.54m Δ
  ublock-quick-fixes: 247-0, 3h.54m Δ
  easylist: 77604-670, 3h.54m Δ
  easyprivacy: 43548-1074, 3h.54m Δ
  urlhaus-1: 9010-0, 8h.4m
  plowe-0: 3781-1, 8h.4m
  FRA-0: 26864-117, 8h.4m
```

#### Your settings:

- OS/version: Ubuntu 23.10
- Browser/version: Firefox 122.0
- Ad block extension/version: uBlock Origin 1.55.0

#### Other details:

It seems to happen because the ID is `gdpr_consent`:
```html
<div id="gdpr_consent" class="gdpr_module_1"> <span class="custom-checkbox"> <label class="psgdpr_consent_message"> <input id="psgdpr_consent_checkbox_1" name="psgdpr_consent_checkbox" type="checkbox" value="1" class="psgdpr_consent_checkboxes_1"> <span><i class="material-icons rtl-no-flip checkbox-checked psgdpr_consent_icon"></i></span> <span>J'accepte <a href="/content/3-conditions-g%C3%A9n%C3%A9rales-de-vente" title="veritable potager"> les conditions générales et la politique de confidentialité </a></span> </label> </span></div>
```
