### ISSUE TITLE
EL(breakage): 08dragon.com

### ISSUE THREAD

**Issue by seia-soto** [easylist/easylist#18435]
#### List the website(s) you're having issues with:

```
https://08dragon.com/map
```

#### What happens?

False positive.

#### Screenshot(s) 

<img width="2560" alt="image" src="https://github.com/easylist/easylist/assets/30369714/c7301619-4c64-421d-817c-d206b86d4a27">

#### Filter lists you're using:

```
listset (total-discarded, last-updated):
 added:
  https://github.com/yous/YousList/raw/master/youslist.txt: 8200-0, 15h.7m
  https://seia-soto.github.io/userscripts/asdefuser.filters.txt: 3-0, 15h.7m
  block-lan: 56-0, 6d.16h.45m
  curben-phishing: 88580-20, 15h.7m
  dpollock-0: 11632-12, 6d.16h.45m
  fanboy-thirdparty_social: 68-0, 6d.16h.45m
 default:
  user-filters: 7-2, never
  easylist: 80069-265, 3h.7m
  easyprivacy: 43615-171, 4h.7m
  plowe-0: 3786-1549, 6d.16h.46m
  ublock-badware: 7804-144, 4h.7m
  ublock-filters: 36914-213, 4h.7m
  ublock-privacy: 990-6, 6d.16h.46m
  ublock-quick-fixes: 151-8, 4h.7m
  ublock-unbreak: 2206-31, 4h.7m
  urlhaus-1: 8480-0, 15h.8m
```

#### Your settings:

- OS/version: 
- Browser/version: 
- Ad block extension/version: 

```
macOS: arm64 14.2.1 (23C71)
uBlock Origin: 1.54.0
Chromium: 118
```

#### Other details:

Caused by:

```adb
##[data-ez-name]
```

Resolvable by:

```
08dragon.com#@#[data-ez-name]
```
