### ISSUE TITLE
www.packeasy.ch

### ISSUE THREAD

**Issue by Rudloff** [easylist/easylist#19814]
#### List the website(s) you're having issues with:

`https://www.packeasy.ch/fr`

#### What happens?

I can't interact with the page when Easylist Cookie List is enabled.

#### Screenshot(s) 

![image](https://github.com/user-attachments/assets/c6057c6a-5cbc-4e7f-88af-269ab76e6c4c)

#### Filter lists you're using:

```yaml
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 67844-16516, never
  ublock-cookies-easylist: 1545-6, 1m
 default:
  user-filters: 0-0, never
  ublock-filters: 39797-118, 1m
  ublock-badware: 10331-6, 1m
  ublock-privacy: 1052-4, 1m
  ublock-unbreak: 2542-1, 1m
  ublock-quick-fixes: 128-8, 1m
  easylist: 85101-179, 1m
  easyprivacy: 52959-65, 1m
  urlhaus-1: 28705-0, 1m
  plowe-0: 3556-997, 1m
  FRA-0: 24884-434, 1m
```

#### Your settings:

- OS/version: Ubuntu 23.10
- Browser/version: Firefox 128.0.3
- Ad block extension/version: uBlock Origin 1.59.0
