### ISSUE TITLE
stash.clash.gg: ads

### ISSUE THREAD

**Issue by 3kh0** [easylist/easylist#21002]
#### List the website(s) you're having issues with:

https://stash.clash.gg/

#### What happens?

Ads still show

#### Screenshot(s) 

![image](https://github.com/user-attachments/assets/e48e36c5-b7e2-45b6-817f-ef28d50d8bf3)

![image](https://github.com/user-attachments/assets/ab3facac-be55-4fc8-8690-2676a3d592cb)

![image](https://github.com/user-attachments/assets/aaa285ae-d9a6-4c47-a206-061927b3084f)

#### Filter lists you're using:

```
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41075-125, 3m
  ublock-badware: 12065-1, 3m
  ublock-privacy: 1828-27, 3m
  ublock-unbreak: 2608-1, 3m
  ublock-quick-fixes: 190-13, 3m
  easylist: 79094-131, 3m
  adguard-spyware-url: 1882-135, 3m
  easyprivacy: 53255-52, 3m
  urlhaus-1: 23930-0, 3m
  curben-phishing: 775-0, 3m
  plowe-0: 3545-992, 3m
  LegitimateURLShortener: 2701-167, 3m
```

#### Your settings:

- OS/version: Alpine Linux
- Browser/version: Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0
- Ad block extension/version: uBlock Origin 1.61.2
