### ISSUE TITLE
polygonscan.com: ads

### ISSUE THREAD

**Issue by 3kh0** [easylist/easylist#21003]
#### List the website(s) you're having issues with:

https://polygonscan.com/

https://polygonscan.com/tx/0x6c8c59e3846846386f6c8c8c0ee0f2ba96a50bce0994ba28d079d3534cd3b63c

https://polygonscan.com/token/0x3c499c542cef5e3811e1192ce70d8cc03d5c3359

#### What happens?

Small text ads are still seen. If the ad does not show, refresh the page as sometimes they hide.

#### Screenshot(s) 

![image](https://github.com/user-attachments/assets/62b96889-0a7c-4409-95a3-6c46e6f93389)

![image](https://github.com/user-attachments/assets/8832f0ee-395f-4a37-b7e6-beabecd3f8d3)

![image](https://github.com/user-attachments/assets/021ee23d-70b0-414b-adb6-5b8efc9b4270)

#### Filter lists you're using:

```
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 41075-125, 1m
  ublock-badware: 12065-1, 1m
  ublock-privacy: 1852-33, 1m
  ublock-unbreak: 2608-1, 1m
  ublock-quick-fixes: 194-13, 1m
  easylist: 79094-131, 1m
  adguard-spyware-url: 1882-135, 1m
  easyprivacy: 53247-44, 1m
  urlhaus-1: 23930-0, 1m
  curben-phishing: 775-0, 1m
  plowe-0: 3545-992, 1m
  LegitimateURLShortener: 2701-167, 1m
```

#### Your settings:

- OS/version: Alpine Linux
- Browser/version: Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0
- Ad block extension/version: uBlock Origin 1.61.2
