### ISSUE TITLE
darkreader.org: ads

### ISSUE THREAD

**Issue by solonovamax** [easylist/easylist#21047]
#### List the website(s) you're having issues with:

- https://darkreader.org/
- https://darkreader.org/blog/g-search-crash/

#### What happens?

on the dark reader website, there are several different places that ads for [Honey](https://www.joinhoney.com/) and [Pie](https://www.pie.org/) are inserted into the page, however are hidden by default. However, I *believe* that they can be randomly enabled as-per reports by other users on youtube.

#### Screenshot(s) 

![image](https://github.com/user-attachments/assets/0fa8d4ab-a96d-4fc4-abd4-5bb189625f63)
![image](https://github.com/user-attachments/assets/6842b92b-3445-4333-943b-518e97b91b45)
![image](https://github.com/user-attachments/assets/f410a18c-c77e-4663-a0d9-a1d403123c93)
![image](https://github.com/user-attachments/assets/b52e6675-f756-42f7-96b2-98f353497e32)
![image](https://github.com/user-attachments/assets/a79761ac-6e63-4442-8b67-34524dd7e5bb)

#### Filter lists you're using:

from ublock's support tab:
```yml
added:
  https://cdn.jsdelivr.net/gh/NanoMeow/MDLMirror@master/hosts.txt: 1104-0, 1d.19m
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 84267-187, 1d.19m
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 18m
  https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7252-0, 1d.19m
  https://raw.githubusercontent.com/gioxx/xfiles/master/filtri.txt: 5895-16, 8d.22h.47m
  https://secure.fanboy.co.nz/enhancedstats.txt: 0-0, 1d.18m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 103286-25086, 1d.21h.40m
  https://secure.fanboy.co.nz/fanboy-problematic-sites.txt: 0-0, 1d.20m
  https://secure.fanboy.co.nz/r/fanboy-complete.txt: 132474-1558, 1d.19m
  https://secure.fanboy.co.nz/r/fanboy-ultimate.txt: 216552-216534, 1d.19m
  https://winhelp2002.mvps.org/hosts.txt: 8729-437, 1d.21h.41m
  adguard-generic: 93847-6562, 1d.19m
  [22 lists not shown]: [too many]
default:
  user-filters: 14-0, never
  ublock-filters: 40211-493, 1h.18m Δ
  ublock-badware: 12139-31, 1h.18m Δ
  ublock-privacy: 1871-105, 1h.18m Δ
  ublock-unbreak: 2606-36, 1h.18m Δ
  ublock-quick-fixes: 219-13, 1h.18m Δ
  easylist: 79208-79196, 1h.18m Δ
  easyprivacy: 53259-53252, 1h.18m Δ
  urlhaus-1: 23440-0, 18m
  plowe-0: 3545-1636, 5d.42m
```

#### Your settings:

- OS/version: Arch Linux 6.12.8-arch1-1 x86_64
- Browser/version: Firefox Nightly 135.0b3
- Ad block extension/version: uBlock Origin 1.61.2

#### Other details:

for more details, see: https://tech.lgbt/@solonovamax/113818973473868549

Here are some blocking rules for the ads on the page:
```
darkreader.org##darkreader-inside-post
darkreader.org##darkreader-backers-top-short
darkreader.org##darkreader-backers-header
darkreader.org##darkreader-backers-side
darkreader.org##darkreader-support-us
darkreader.org##.pie-help
darkreader.org##darkreader-questions
darkreader.org##.v2-banner-pie
! the following are not related to pie/honey, but are incredibly annoying and very ad-like
darkreader.org##.v2-banner-mobile
darkreader.org##.v2-banner-safari
darkreader.org##darkreader-ios-static
darkreader.org##darkreader-ios-top
darkreader.org##darkreader-ios-side
darkreader.org##darkreader-backers-side
darkreader.org##darkreader-pay-tiers
darkreader.org##darkreader-mobile-side
darkreader.org##darkreader-mobile-top-short
darkreader.org##darkreader-plus-tiers
darkreader.org##darkreader-safari-top-short
darkreader.org##darkreader-donate-mascot
! see: https://github.com/darkreader/darkreader.org/blob/22e0eeba866e09d08104e5838fe31cba75be13dc/www/elements/sponsors-graph.js#L61-L78
darkreader.org##darkreader-backers-graph
! tracking script
! statistics.js was previously blocked, but I believe they changed it.
! statistics.js is now just "void 0;" yes. that's the entire script.
||darkreader.org/elements/stats.js
! these rules already exist, but they use darkreader.app instead of darkreader.org
||errors.darkreader.org^
! on https://darkreader.org/goodluck/, everything under <section class="recommendations"> *except* <p class="come-again"> should be blocked. unsure how to write a rule that does this
! see: https://github.com/darkreader/darkreader.org/blob/22e0eeba866e09d08104e5838fe31cba75be13dc/www/goodluck/index.html#L24-L29
```

I think this is *most* of them, although it might not be all.
I added nearly all the elements from this folder, as they're all basically ads: https://github.com/darkreader/darkreader.org/tree/22e0eeba866e09d08104e5838fe31cba75be13dc/www/elements
