### ISSUE TITLE
kontostand.at: breakage due to missing cookie banner script

### ISSUE THREAD

**Issue by profiluefter** [easylist/easylist#21093]
#### List the website(s) you're having issues with:

`https://www.kontostand.at/WebportalAPK/#/login`

#### What happens?

The page blocks doing anything because it detected that it was unable to ask the user for their cookie consent and states that it can't work without it.
It should just be a login prompt.

#### Screenshot(s):

![Image](https://github.com/user-attachments/assets/2bfe5e72-355e-43f2-bb23-35e4f6d0b798)

#### Filter lists you're using:

according to the uBlock support feature:
```
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 48992-174, now
  ublock-annoyances: 5979-37, 1h.13m Δ
  DEU-0: 7863-30, now
  ublock-cookies-easylist: 2258-7, now
 default:
  user-filters: 16-1, never
  ublock-filters: 40148-115, 1h.13m Δ
  ublock-badware: 12294-6, 1h.13m Δ
  ublock-privacy: 1920-33, 1h.13m Δ
  ublock-unbreak: 2609-1, 1h.13m Δ
  easylist: 70784-151, 1h.13m Δ
  easyprivacy: 53286-44, 1h.13m Δ
  urlhaus-1: 23955-0, now
  plowe-0: 3548-994, now
  ublock-quick-fixes: 244-42, 1h.13m Δ
```

#### Your settings:

- OS/version: Arch Linux (latest)
- Browser/version: Firefox 134.0.1
- Ad block extension/version: uBlock Origin 1.62.0

#### Other details:

I have created this filter using the uBlock Logging tool and with it (essentially unblocking that url) the page works again.

`@@||www.kontostand.at/WebportalAPK/js/cookie-banner.js$script,domain=www.kontostand.at`

By searching for `cookie-banner.js` I've seen that most likely the script gets blocked by this line:

https://github.com/easylist/easylist/blob/b3b8def704590f2fba58bf9a59292143b47437fb/easylist_cookie/easylist_cookie_general_block.txt#L159

and could probably be fixed in a similar way to this line:

https://github.com/easylist/easylist/blob/b3b8def704590f2fba58bf9a59292143b47437fb/easylist_cookie/easylist_cookie_allowlist.txt#L50

However I've just noticed that that only fixes the obvious issue that the page doesn't want to do anything. I think whitelisting some CSS rules is also necessary because now the page doesn't allow any input and is not scrollable.
