### ISSUE TITLE
wco.tv

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#21790]
#### List the website(s) you're having issues with: 
wco.tv

#### What happens?
Large white spaces are visible.

#### Screenshot(s):

![Image](https://github.com/user-attachments/assets/aff105d9-1be9-48c0-a484-be57794618d6)
![Image](https://github.com/user-attachments/assets/dd08b8a2-7520-4e8d-acef-95adcd078a08)

#### Filter lists you're using:

From uBO's troubleshooting page:
```
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6080-12, 2h.49m
 default:
  user-filters: 53-0, never
  ublock-filters: 40478-352, 55m Δ
  ublock-badware: 12186-26, 55m Δ
  ublock-privacy: 2824-3, 55m Δ
  ublock-unbreak: 2619-2, 55m Δ
  ublock-quick-fixes: 383-2, 55m Δ
  easylist: 68996-440, 55m Δ
  easyprivacy: 54265-606, 55m Δ
  urlhaus-1: 37465-1, 2h.52m
  plowe-0: 3441-0, 2h.52m
  ROU-1: 1463-11, 2h.52m
```

#### Your settings:

- OS/version: Windows 11
- Browser/version: Opera 118.0.5461.83
- Ad block extension/version: uBlock Origin

#### Other details:

These filters fix the problem:
```
wco.tv##[style^="float:right;"]:has([class^="reklam"])
wco.tv###sidebar_today > div[style^="float:right;"]
```
