### ISSUE TITLE
newsweek.com

### ISSUE THREAD

**Issue by DRSDavidSoft** [easylist/easylist#6589]
### List the website(s) you're having issues:

```
https://www.newsweek.com/monopoly-man-made-appearance-equifax-and-wells-fargo-hearings-heres-why-677984
```

### What happens?

Empty space (e.g. `min-height: 250px`) for ad wrappers are shown.

### What needs to be blocked?

```
##[id^=dfp-ad-][id$=-wrapper]
```

### Screenshot

_(Notice the empty space in the middle of post, it's a `#dfp-ad-right2-wrapper` element)_

![screenshot1](https://user-images.githubusercontent.com/4673812/101021931-e3944680-3585-11eb-9b10-c496a26da61a.png)

### Class names

```css
                .not-logged-in #dfp-ad-top-wrapper {
                    min-height: 270px
                }

                .not-logged-in #dfp-ad-right1-wrapper {
                    min-height: 250px
                }

                .not-logged-in #dfp-ad-right2-wrapper {
                    min-height: 250px
                }

                .not-logged-in #dfp-ad-right4-wrapper {
                    min-height: 250px
                }

                .not-logged-in #dfp-ad-bottom-wrapper {
                    min-height: 110px
                }

                .not-logged-in .dfp-ad-lazy {
                    min-height: 250px
                }
```

### List Subscriptions you're using:

```
uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak

AdGuard Base
AdGuard Mobile Ads
EasyList

AdGuard Tracking Protection
EasyPrivacy
Fanboy’s Enhanced Tracking List

AdGuard Annoyances
EasyList Cookie
Fanboy’s Annoyance
uBlock filters – Annoyances
```

### Your settings

- OS/version: Windows 10
- Browser/version: Chrome 86.0.4240.198
- Adblock Extension/version: uBlock Origin 1.31.0
